package com.firefly.store.jdbc;

import com.firefly.batch.*;
import javax.sql.DataSource;
import java.sql.SQLException;
import java.sql.Timestamp;
import java.time.Instant;
import java.util.*;

/** JDBC batch aggregate with monotonic fencing and immutable attempt rows. */
public final class JdbcBatchRepository implements BatchRepository {
    private final DataSource dataSource;
    public JdbcBatchRepository(DataSource dataSource) { this.dataSource=Objects.requireNonNull(dataSource,"dataSource"); }
    public void save(BatchExecution e) {
        String sql="insert into firefly_batch_execution(root_execution_id,job_id,total_shards,completed_shards,failed_shards,retried_shards,input_records,output_records,progress_percent,sla_status,started_at,deadline,updated_at,fencing_token) values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
        try(var c=dataSource.getConnection();var p=c.prepareStatement(sql)){BatchProgress b=e.progress();p.setString(1,e.rootExecutionId());p.setString(2,e.jobId());p.setInt(3,b.totalShards());p.setInt(4,b.completedShards());p.setInt(5,b.failedShards());p.setInt(6,b.retriedShards());p.setLong(7,b.inputRecords());p.setLong(8,b.outputRecords());p.setInt(9,b.percent());p.setString(10,b.slaStatus().name());p.setTimestamp(11,Timestamp.from(e.startedAt()));p.setTimestamp(12,Timestamp.from(e.deadline()));p.setTimestamp(13,Timestamp.from(b.updatedAt()));p.setLong(14,0);p.executeUpdate();}catch(SQLException x){if(!constraint(x))throw new JdbcException("failed to save batch",x);}
    }
    public Optional<BatchExecution> find(String id){String q="select root_execution_id,job_id,total_shards,completed_shards,failed_shards,retried_shards,input_records,output_records,progress_percent,sla_status,started_at,deadline,updated_at from firefly_batch_execution where root_execution_id=?";try(var c=dataSource.getConnection();var p=c.prepareStatement(q)){p.setString(1,id);try(var r=p.executeQuery()){if(!r.next())return Optional.empty();BatchProgress b=new BatchProgress(r.getInt(3),r.getInt(4),r.getInt(5),r.getInt(6),r.getLong(7),r.getLong(8),r.getInt(9),r.getTimestamp(13).toInstant(),BatchSlaStatus.valueOf(r.getString(10)));return Optional.of(new BatchExecution(r.getString(1),r.getString(2),b,r.getTimestamp(11).toInstant(),r.getTimestamp(12).toInstant()));}}catch(SQLException x){throw new JdbcException("failed to read batch",x);}}
    public boolean saveProgress(String id, BatchProgress b, long fence){String q="update firefly_batch_execution set completed_shards=?,failed_shards=?,retried_shards=?,input_records=?,output_records=?,progress_percent=?,sla_status=?,updated_at=?,fencing_token=? where root_execution_id=? and fencing_token<=?";try(var c=dataSource.getConnection();var p=c.prepareStatement(q)){p.setInt(1,b.completedShards());p.setInt(2,b.failedShards());p.setInt(3,b.retriedShards());p.setLong(4,b.inputRecords());p.setLong(5,b.outputRecords());p.setInt(6,b.percent());p.setString(7,b.slaStatus().name());p.setTimestamp(8,Timestamp.from(b.updatedAt()));p.setLong(9,fence);p.setString(10,id);p.setLong(11,fence);return p.executeUpdate()==1;}catch(SQLException x){throw new JdbcException("failed to update batch progress",x);}}
    public boolean saveShardResult(BatchShardResult r,long fence){String q="insert into firefly_batch_shard(root_execution_id,shard_index,attempt,status,input_records,output_records,checkpoint_id,checksum,error_message,completed_at) select ?,?,?,?,?,?,?,?,?,? where exists (select 1 from firefly_batch_execution where root_execution_id=? and fencing_token<=?)";try(var c=dataSource.getConnection();var p=c.prepareStatement(q)){p.setString(1,r.rootExecutionId());p.setInt(2,r.shardIndex());p.setInt(3,r.attempt());p.setString(4,r.status());p.setLong(5,r.inputRecords());p.setLong(6,r.outputRecords());p.setString(7,r.checkpointId());p.setString(8,r.checksum());p.setString(9,r.errorMessage());p.setTimestamp(10,Timestamp.from(r.completedAt()));p.setString(11,r.rootExecutionId());p.setLong(12,fence);return p.executeUpdate()==1;}catch(SQLException x){if(constraint(x))return false;throw new JdbcException("failed to save shard result",x);}}
    public List<BatchShardResult> listShardResults(String id){List<BatchShardResult> out=new ArrayList<>();String q="select root_execution_id,shard_index,attempt,status,input_records,output_records,checkpoint_id,checksum,error_message,completed_at from firefly_batch_shard where root_execution_id=? order by shard_index,attempt";try(var c=dataSource.getConnection();var p=c.prepareStatement(q)){p.setString(1,id);try(var r=p.executeQuery()){while(r.next())out.add(new BatchShardResult(r.getString(1),r.getInt(2),r.getInt(3),r.getString(4),r.getLong(5),r.getLong(6),r.getString(7),r.getString(8),r.getString(9),r.getTimestamp(10).toInstant()));}}catch(SQLException x){throw new JdbcException("failed to list shard results",x);}return List.copyOf(out);}
    private boolean constraint(SQLException e){String s=e.getSQLState();return "23505".equals(s)||"23000".equals(s);}
}
